### ISSUE TITLE
Class attribute cannot be changed

### ISSUE THREAD

**Issue by bgillieron** [szaboolcs/yii2-invisible-recaptcha#3]
Hi,

Thanks for the nice plugin.

Just want to report an issue, if you set "class" attribute for the button it does not change the actual class as widget() in yii uses this specifically it seems:
in 

> yii2/base/widget

 line 135 : $config['class'] = get_called_class();
So if i change the value in the widget call (for example in my case I don't want btn-block:
`<?= InvisibleRecaptcha::widget([
            'name'         => 'Envoyer',
            'formSelector' => '#contact-form',
            'class'        => 'btn btn-default'
        ]);
      ?>`
Then it does not change the class attribute of the widget, it still remains as default:

> btn btn-default btn-block
Would maybe be better if you could rename that attribute in the code to something else like btnClass etc.

Thanks,

**Comment by bgillieron** [comment]
I didnt notice before but @pilehead already created a pull request for this would be nice if you could update the repo

**Comment by szaboolcs** [comment]
Hi,

thx for your notice, I accepted the pull request..
